sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t polux0/ci-cd -f Dockerfile.dev .

script:
    - docker run -e CI=true polux0/ci-cd npm run test -- --coverage
